name: Lunaticoscraft
version: '1.0-SNAPSHOT'
main: lunaticoscraft.lunaticoscraft.Lunaticoscraft
api-version: 1.19
authors: [ evertonwingert ]
commands:
  race:
    description: Set a race
    usage: /race <race>
